/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.42
 * Generated at: 2013-11-09 02:58:17 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp.youyaku;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class BbsAdmin_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/tld/myTag.tld", Long.valueOf(1196401734000L));
    _jspx_dependants.put("/WEB-INF/jsp/common.jsp", Long.valueOf(1383532455427L));
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script language=\"JavaScript\"\r\n");
      out.write("\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope['app.context']}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/youyaku/CheckUtil.js\"></script>\r\n");
      out.write("<script language=\"JavaScript\">\r\n");
      out.write("<!--\r\n");
      out.write("function chk(){\r\n");
      out.write("\tvar c = new CheckUtil();\r\n");
      out.write("\tc.dateTypeCheck(document.fm.old.value,\"削除範囲\");\r\n");
      out.write("\tc.rangeCheck(document.fm.num.value,999,1,\"記事番号\");\r\n");
      out.write("\treturn c.getErrors();\r\n");
      out.write("}\r\n");
      out.write("//-->\r\n");
      out.write("</script>\r\n");
      out.write("<form method=\"POST\" action=\"BbsAdminAction\" name=\"fm\" onsubmit=\"return chk()\">\r\n");
      out.write("<table border=\"1\" width=\"600\" bordercolordark=\"#FFffFF\">\r\n");
      out.write("<tr>\r\n");
      out.write("\t<th>処理</th>\r\n");
      out.write("\t<th>概要</th>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr height=\"50\">\r\n");
      out.write("\t<th><input type=\"submit\" name=\"sbm\" value=\"古い記事の整理\" /></th>\r\n");
      out.write("\t<td height=\"50\"><input type=\"text\" name=\"old\"\r\n");
      out.write("\t\t\tsize=\"12\" maxlength=\"10\" style=\"ime-mode:disabled;\" />\r\n");
      out.write("\t\t（YYYY/MM/DD）より前の記事を一括削除します</td>\r\n");
      out.write("</tr>\r\n");
      out.write("<tr height=\"50\">\r\n");
      out.write("\t<th><input type=\"submit\" name=\"sbm\" value=\"特定記事の削除\" /></th>\r\n");
      out.write("\t<td>No.<input type=\"text\" name=\"num\" size=\"3\" maxlength=\"3\"\r\n");
      out.write("\t\tstyle=\"ime-mode:disabled;\" />の記事を強制的に削除します</td>\r\n");
      out.write("</tr>\r\n");
      out.write("</table>\r\n");
      out.write("</form>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
