/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.42
 * Generated at: 2013-11-13 10:10:21 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp.youyaku;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class BbsNew_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/tld/myTag.tld", Long.valueOf(1196401734000L));
    _jspx_dependants.put("/WEB-INF/jsp/common.jsp", Long.valueOf(1383532455427L));
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script language=\"JavaScript\"\r\n");
      out.write("\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope['app.context']}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/youyaku/CheckUtil.js\"></script>\r\n");
      out.write("<script language=\"JavaScript\">\r\n");
      out.write("<!--\r\n");
      out.write("function chk(){\r\n");
      out.write("\tvar c = new CheckUtil();\r\n");
      out.write("\tc.requiredCheck(document.fm.title.value,\"タイトル\");\r\n");
      out.write("\tc.lengthCheck(document.fm.title.value,50,\"タイトル\");\r\n");
      out.write("\tc.requiredCheck(document.fm.source.value,\"記事提供元の名称\");\r\n");
      out.write("\tc.lengthCheck(document.fm.source.value,50,\"記事提供元の名称\");\r\n");
      out.write("\tc.requiredCheck(document.fm.url.value,\"URL\");\r\n");
      out.write("\treturn c.getErrors();\r\n");
      out.write("}\r\n");
      out.write("function charaLen(str){\r\n");
      out.write("\t  val=str.replace(/\\s|　/g,\"\");\r\n");
      out.write("\t  val=val.length;\r\n");
      out.write("\t   document.getElementById('len').value = val;\r\n");
      out.write("}\r\n");
      out.write("-->\r\n");
      out.write("</script>\r\n");
      out.write("<form method=\"POST\" action=\"BbsNewAction\" name=\"fm\" onsubmit=\"return chk()\">\r\n");
      out.write("<table border=\"1\" width=\"500\" cellpadding=\"5\" >\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<th align=\"right\" nowrap>タイトル</th>\r\n");
      out.write("\t\t<td><input type=\"text\" name=\"title\" size=\"97\" maxlength=\"50\"\r\n");
      out.write("\t\t\t\t\tstyle=\"ime-mode:active;\" /></td>\r\n");
      out.write("\t</tr><tr>\r\n");
      out.write("\t\t<th align=\"right\">要約する文章</th>\r\n");
      out.write("\t\t<td colspan=\"2\">\r\n");
      out.write("\t\t\t<textarea id=\"s\" name=\"article\"  cols=\"73\" rows=\"15\" onKeyup=\"charaLen(value);\"></textarea>\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t</tr><tr>\r\n");
      out.write("\t\t<th align=\"right\" nowrap>文字数</th>\r\n");
      out.write("\t\t<td><input type=\"text\" id=\"len\" value =\"0\" name=\"charalen\" size=\"5\" maxlength=\"3\" /></td>\r\n");
      out.write("\t</tr><tr>\r\n");
      out.write("\t\t<th align=\"right\" nowrap>記事提供元の名称</th>\r\n");
      out.write("\t\t<td><input type=\"text\" name=\"source\" size=\"97\" maxlength=\"50\" /></td>\r\n");
      out.write("\t</tr><tr>\r\n");
      out.write("\t\t<th align=\"right\" nowrap>記事提供元のURL</th>\r\n");
      out.write("\t\t<td><input type=\"text\" name=\"url\" size=\"97\"  /></td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t</table>\r\n");
      out.write("\t<input type=\"submit\" name=\"sbm\" value=\"投稿\" />\r\n");
      out.write("\t<input type=\"reset\" value=\"リセット\" />\r\n");
      out.write("</form>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
